language: csharp
solution: ./StardewNewsFeed/StardewNewsFeed.sln
install:
    - nuget restore ./StardewNewsFeed/StardewNewsFeed.sln
    - xbuild ./StardewNewsFeed/StardewNewsFeed.sln
mono:
    - 5.16.1
    - latest
branches:
    only:
    - master
    - develop